
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Unity-iPhone.xcodeproj")
    match(type: "appstore")
    gym(
      export_method: "app-store",
      project: "Unity-iPhone.xcodeproj",
      # workspace: "Unity-iPhone.xcworkspace", #one of project or workspace depends on if you use pods
      scheme: "Unity-iPhone",
    )
    upload_to_testflight
  end
end

